'use strict'; // code generated by pbf v3.2.1

// DAMFile ========================================

var DAMFile = exports.DAMFile = {};

DAMFile.read = function (pbf, end) {
    return pbf.readFields(DAMFile._readField, {chunk: [], quantized_chunk: []}, end);
};
DAMFile._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.chunk.push(Chunk.read(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 2) obj.quantized_chunk.push(QuantizedChunk.read(pbf, pbf.readVarint() + pbf.pos));
};
DAMFile.write = function (obj, pbf) {
    if (obj.chunk) for (var i = 0; i < obj.chunk.length; i++) pbf.writeMessage(1, Chunk.write, obj.chunk[i]);
    if (obj.quantized_chunk) for (i = 0; i < obj.quantized_chunk.length; i++) pbf.writeMessage(2, QuantizedChunk.write, obj.quantized_chunk[i]);
};

// Chunk ========================================

var Chunk = exports.Chunk = {};

Chunk.read = function (pbf, end) {
    return pbf.readFields(Chunk._readField, {vertices: null, faces: null, chunk_name: "", material_name: ""}, end);
};
Chunk._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.vertices = Vertices.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 2) obj.faces = Faces.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 3) obj.chunk_name = pbf.readString();
    else if (tag === 4) obj.material_name = pbf.readString();
};
Chunk.write = function (obj, pbf) {
    if (obj.vertices) pbf.writeMessage(1, Vertices.write, obj.vertices);
    if (obj.faces) pbf.writeMessage(2, Faces.write, obj.faces);
    if (obj.chunk_name) pbf.writeStringField(3, obj.chunk_name);
    if (obj.material_name) pbf.writeStringField(4, obj.material_name);
};

// QuantizedChunk ========================================

var QuantizedChunk = exports.QuantizedChunk = {};

QuantizedChunk.read = function (pbf, end) {
    return pbf.readFields(QuantizedChunk._readField, {chunk_name: "", material_name: "", vertices: null, uvs: [], faces: null}, end);
};
QuantizedChunk._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.chunk_name = pbf.readString();
    else if (tag === 2) obj.material_name = pbf.readString();
    else if (tag === 3) obj.vertices = QuantizedVertices.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.uvs.push(QuantizedUVs.read(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 5) obj.faces = Faces.read(pbf, pbf.readVarint() + pbf.pos);
};
QuantizedChunk.write = function (obj, pbf) {
    if (obj.chunk_name) pbf.writeStringField(1, obj.chunk_name);
    if (obj.material_name) pbf.writeStringField(2, obj.material_name);
    if (obj.vertices) pbf.writeMessage(3, QuantizedVertices.write, obj.vertices);
    if (obj.uvs) for (var i = 0; i < obj.uvs.length; i++) pbf.writeMessage(4, QuantizedUVs.write, obj.uvs[i]);
    if (obj.faces) pbf.writeMessage(5, Faces.write, obj.faces);
};

// QuantizedVertices ========================================

var QuantizedVertices = exports.QuantizedVertices = {};

QuantizedVertices.read = function (pbf, end) {
    return pbf.readFields(QuantizedVertices._readField, {quantization: 0, translation: [], x: [], y: [], z: []}, end);
};
QuantizedVertices._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.quantization = pbf.readFloat();
    else if (tag === 2) pbf.readPackedFloat(obj.translation);
    else if (tag === 3) pbf.readPackedSVarint(obj.x);
    else if (tag === 4) pbf.readPackedSVarint(obj.y);
    else if (tag === 5) pbf.readPackedSVarint(obj.z);
};
QuantizedVertices.write = function (obj, pbf) {
    if (obj.quantization) pbf.writeFloatField(1, obj.quantization);
    if (obj.translation) pbf.writePackedFloat(2, obj.translation);
    if (obj.x) pbf.writePackedSVarint(3, obj.x);
    if (obj.y) pbf.writePackedSVarint(4, obj.y);
    if (obj.z) pbf.writePackedSVarint(5, obj.z);
};

// Faces ========================================

var Faces = exports.Faces = {};

Faces.read = function (pbf, end) {
    return pbf.readFields(Faces._readField, {faces: []}, end);
};
Faces._readField = function (tag, obj, pbf) {
    if (tag === 1) pbf.readPackedVarint(obj.faces, true);
};
Faces.write = function (obj, pbf) {
    if (obj.faces) pbf.writePackedVarint(1, obj.faces);
};

// QuantizedUVs ========================================

var QuantizedUVs = exports.QuantizedUVs = {};

QuantizedUVs.read = function (pbf, end) {
    return pbf.readFields(QuantizedUVs._readField, {name: "", quantization: 0, u: [], v: []}, end);
};
QuantizedUVs._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.name = pbf.readString();
    else if (tag === 2) obj.quantization = pbf.readFloat();
    else if (tag === 3) pbf.readPackedSVarint(obj.u);
    else if (tag === 4) pbf.readPackedSVarint(obj.v);
};
QuantizedUVs.write = function (obj, pbf) {
    if (obj.name) pbf.writeStringField(1, obj.name);
    if (obj.quantization) pbf.writeFloatField(2, obj.quantization);
    if (obj.u) pbf.writePackedSVarint(3, obj.u);
    if (obj.v) pbf.writePackedSVarint(4, obj.v);
};

// Vertices ========================================

var Vertices = exports.Vertices = {};

Vertices.read = function (pbf, end) {
    return pbf.readFields(Vertices._readField, {xyz: [], uv: []}, end);
};
Vertices._readField = function (tag, obj, pbf) {
    if (tag === 1) pbf.readPackedFloat(obj.xyz);
    else if (tag === 2) pbf.readPackedFloat(obj.uv);
};
Vertices.write = function (obj, pbf) {
    if (obj.xyz) pbf.writePackedFloat(1, obj.xyz);
    if (obj.uv) pbf.writePackedFloat(2, obj.uv);
};
